# Generated by Django 6.0.3 on 2026-04-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_bio_alter_profile_favorite_cities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('owner', 'Owner'), ('agent', 'Agent'), ('admin', 'Admin')], default='buyer', max_length=10),
        ),
    ]
