# Generated by Django 6.0.3 on 2026-04-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbylocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='nearbylocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='nearbylocation',
            name='place_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='ai_generated_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='image_features_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='seo_meta_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='nearbylocation',
            name='place_type',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('school', 'School'), ('college', 'College / University'), ('park', 'Park'), ('mall', 'Shopping Mall'), ('station', 'Railway Station'), ('metro', 'Metro Station'), ('airport', 'Airport'), ('supermarket', 'Supermarket'), ('restaurant', 'Restaurant'), ('bus_stand', 'Bus Stand'), ('gym', 'Gym / Fitness'), ('bank', 'Bank'), ('atm', 'ATM'), ('pharmacy', 'Pharmacy'), ('cinema', 'Cinema / Multiplex'), ('temple', 'Temple'), ('mosque', 'Mosque'), ('church', 'Church'), ('office_park', 'IT Park / Office Hub'), ('fuel', 'Petrol Pump'), ('other', 'Other')], max_length=50),
        ),
    ]
