# Generated by Django 6.0.3 on 2026-04-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_options_alter_propertyimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='nearby_other_places',
            field=models.JSONField(blank=True, default=list, help_text='Any other important nearby daily-life places'),
        ),
    ]
