# Generated by Django 6.0.3 on 2026-04-15 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertyimage_ai_visual_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('intent', models.CharField(blank=True, choices=[('buy', 'Buy'), ('rent', 'Rent'), ('invest', 'Invest')], max_length=20, null=True)),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('plot', 'Plot'), ('commercial', 'Commercial'), ('office', 'Office'), ('shop', 'Shop'), ('farmland', 'Farmland')], max_length=20, null=True)),
                ('bhk', models.CharField(blank=True, max_length=10, null=True)),
                ('qualification_stage', models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot')], default='cold', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('source', models.CharField(default='chatbot', max_length=50)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='properties.property')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='properties.lead')),
            ],
            options={
                'ordering': ['scheduled_datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'qualification_stage'], name='properties__status_a1fe11_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='properties__created_4f4313_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_agent'], name='properties__assigne_ddde49_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_datetime', 'status'], name='properties__schedul_531ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['lead'], name='properties__lead_id_9f25d4_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['assigned_agent'], name='properties__assigne_fef913_idx'),
        ),
    ]
