from django.contrib import admin
from django.utils.html import format_html

from .models import NearbyLocation, Property, PropertyImage
from .ai_services import generate_comprehensive_seo_data


class PropertyImageInline(admin.TabularInline):
    model = PropertyImage
    extra = 0


class NearbyLocationInline(admin.TabularInline):
    model = NearbyLocation
    extra = 0


def regenerate_seo_content(modeladmin, request, queryset):
    """Admin action to regenerate SEO content for selected properties."""
    updated = 0
    for prop in queryset:
        try:
            seo_data = generate_comprehensive_seo_data(prop)
            prop.ai_generated_description = seo_data["ai_generated_description"]
            prop.seo_meta_description = seo_data["seo_meta_description"]
            prop.seo_keywords = seo_data["seo_keywords"]
            prop.seo_score = seo_data["seo_score"]
            prop.save(update_fields=[
                'ai_generated_description',
                'seo_meta_description',
                'seo_keywords',
                'seo_score'
            ])
            updated += 1
        except Exception as e:
            print(f"Error updating {prop.title}: {e}")

    modeladmin.message_user(request, f'{updated} properties updated with fresh SEO content.')


regenerate_seo_content.short_description = "🔄 Regenerate SEO content for selected properties"


def view_seo_score(modeladmin, request, queryset):
    """Admin action to view SEO scores."""
    for prop in queryset:
        score_color = 'green' if prop.seo_score >= 70 else 'orange' if prop.seo_score >= 50 else 'red'
        print(f"{prop.title}: {prop.seo_score}/100")


view_seo_score.short_description = "📊 View SEO scores"


@admin.register(Property)
class PropertyAdmin(admin.ModelAdmin):
    list_display = (
        'title',
        'city',
        'property_type',
        'price',
        'agent',
        'views_count',
        'seo_score_display',
        'created_at'
    )
    list_filter = ('property_type', 'city', 'is_featured')
    search_fields = ('title', 'city', 'address')
    readonly_fields = (
        'ai_generated_description',
        'seo_meta_description',
        'seo_keywords',
        'seo_score',
        'seo_info_display'
    )
    fieldsets = (
        ('Basic Information', {
            'fields': ('title', 'description', 'property_type', 'city', 'address')
        }),
        ('Pricing & Status', {
            'fields': ('price', 'agent', 'is_featured', 'created_at')
        }),
        ('Location', {
            'fields': ('latitude', 'longitude')
        }),
        ('AI & SEO Content', {
            'fields': (
                'seo_info_display',
                'ai_generated_description',
                'seo_meta_description',
                'seo_keywords',
                'seo_score',
            ),
            'description': '⚙️ Auto-generated by AI. Use "Regenerate SEO content" action to refresh.',
            'classes': ('collapse',)
        }),
        ('Analytics', {
            'fields': ('views_count', 'image_features_json'),
            'classes': ('collapse',)
        }),
    )
    inlines = [PropertyImageInline, NearbyLocationInline]
    actions = [regenerate_seo_content, view_seo_score]

    def seo_score_display(self, obj):
        """Display SEO score with color coding."""
        score = obj.seo_score or 0
        if score >= 70:
            color = 'green'
            label = '✓ Good'
        elif score >= 50:
            color = 'orange'
            label = '⚠ Fair'
        else:
            color = 'red'
            label = '✗ Needs Work'
        return format_html(
            '<span style="color: {}; font-weight: bold;">{}/100 {}</span>',
            color,
            score,
            label
        )

    seo_score_display.short_description = 'SEO Score'

    def seo_info_display(self, obj):
        """Display SEO information summary."""
        if not obj.seo_keywords:
            return "No SEO data yet. Use 'Regenerate SEO content' action."
        
        keywords = obj.seo_keywords.get('primary', [])
        keywords_str = ', '.join(keywords) if keywords else 'None'
        
        return format_html(
            '<div style="padding: 10px; background: #f0f0f0; border-radius: 4px;">'
            '<strong>Primary Keywords:</strong> {}<br/>'
            '<strong>Meta Length:</strong> {} chars<br/>'
            '<strong>Description Length:</strong> {} words'
            '</div>',
            keywords_str,
            len(obj.seo_meta_description or ''),
            len((obj.ai_generated_description or '').split())
        )

    seo_info_display.short_description = 'SEO Information'


@admin.register(PropertyImage)
class PropertyImageAdmin(admin.ModelAdmin):
    list_display = ('property', 'image')


@admin.register(NearbyLocation)
class NearbyLocationAdmin(admin.ModelAdmin):
    list_display = ('name', 'place_type', 'property', 'distance')
