# Generated by Django 6.0.3 on 2026-04-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_add_conversation_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='property',
        ),
    ]
