# Generated by Django 6.0.3 on 2026-04-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_options_remove_message_property'),
        ('properties', '0004_property_nearby_other_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='properties.property'),
        ),
    ]
